service: api
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1

plugins:
  - serverless-appsync-plugin

package:
  exclude:
    - package-lock.json
    - package.json

custom:
  appSync:
    - ${file(appsync-api.yml)}
